name: App Platform - Delete Preview

on:
  pull_request:
    types: [ closed ]

jobs:
  closed:
    runs-on: ubuntu-24.04
    steps:
      - name: delete preview app
        uses: digitalocean/app_action/delete@6a94fd3f3a70f194208a25f800c098bc2fe89d65 # v2.0.9
        with:
          from_pr_preview: "true"
          ignore_not_found: "true"
          token: ${{ secrets.DO_TOKEN }}