name: App Platform - Delete Preview

on:
  pull_request:
    types: [ closed ]

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
      - name: delete preview app
        uses: digitalocean/app_action/delete@v2.0.9
        with:
          from_pr_preview: "true"
          ignore_not_found: "true"
          token: ${{ secrets.DO_TOKEN }}