name: App Platform - Deploy App

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
 deploy-app:
   runs-on: ubuntu-24.04
   steps:
     - name: Checkout repository
       uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
     - name: Deploy the app
       uses: digitalocean/app_action/deploy@6a94fd3f3a70f194208a25f800c098bc2fe89d65 # v2.0.9
       with:
         token: ${{ secrets.DO_TOKEN }} 
         project_id: a420947b-e41a-48b8-8889-febfa138b556