name: do-app

on:
  push:
    branches:
      - main
    paths:
      - 'ghost-app/**'
      - 'ghost-proxy/**'

jobs:
  rebuild:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Rebuild app
      run: doctl apps create-deployment ${{ secrets.DO_APP_ID }} --force-rebuild
